name: ros2-pipeline-test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: ros:jazzy

    steps:
    - uses: actions/checkout@v3

    - run: |
        apt update
        apt install -y python3-colcon-common-extensions python3-rosdep
        rosdep update
        mkdir -p ros2_ci_cd/src
        cp -r . ros2_ci_cd/src/ros2_ci_cd
        cd ros2_ci_cd
        rosdep install --from-paths src -y --ignore-src
        colcon build

    - run: |
        cd ros2_ci_cd
        colcon test
        colcon test-result --verbose