name: ros2-pipeline-test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: ros:jazzy

    steps:
    - uses: actions/checkout@v3

    - run: |
        source /opt/ros/jazzy/setup.bash
        cd ros2_ci_cd
        rosdep install --from-paths src -y --ignore-src
        colcon build

    - run: |
        source /opt/ros/jazzy/setup.bash
        cd ros2_ci_cd
        colcon test
        colcon test-result --verbose